lengths = set(["inches", "in", "feet", "yards", "ft", "yd", "centimeters", "cm", "meters"])

times = set(["second", "minute", "hour", "day", "sec", "min", "hr"])

#rates are generated by using {length} per {second}

digits = set(["1", "2", "3", "4", "5", "6", "7", "8", "9", "0"])

#pre subject qualifiers IMMEDIATELY precede the subject's numerical qualification

pre_subj_len_qualifiers = set(["length is", "height is", "tallness is", "width is"])

pre_subj_depth_qualifiers = set(["depth is", "deepness is"])

#post subject qualifiers IMMEDIATELY follow the subject's numerical qualification

post_subj_len_qualifiers = set(["long", "wide", "tall"])

post_subj_depth_qualifiers = set(["deep", "low", "in length"])

post_subj_rate_qualifiers = set(["rate", "speed"])

post_subj_proximity_qualifiers = set(["away", "from"])

#copulatives indicate something; it can be anything from legnth, status, irrelevant info, etc.
#copulas "couple" things by some existential relationship usually
#eg, "the sky _is_ blue"

#in the frame of word problems, we will use copulatives as an indicator of length qualification

#present tense
singular_copulatives = set(["is"])

plural_copulatives = set(["are"])

of_POS = set(["of"])

queries = set(["how"])
